name: CI

on:
  push:
    branches: [ work ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run integration tests
        env:
          RUNPOD_ENDPOINT: ${{ secrets.RUNPOD_ENDPOINT }}
          PYTHONPATH: src
        run: pytest tests/integration/test_runpod_api.py::test_runpod_live_transcription -vv
