name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install gh cli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          gh --version
          gh run list --limit 1 -R ${{ github.repository }} --json databaseId
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest -q -m "not integration"
      - name: Run integration tests
        env:
          RUNPOD_ENDPOINT: ${{ secrets.RUNPOD_ENDPOINT }}
        run: pytest -q -m "integration"
      - name: Run golden path script
        env:
          RUNPOD_ENDPOINT: ${{ secrets.RUNPOD_ENDPOINT }}
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        run: python scripts/run_e2e_transcription.py
